add hero
OlhaMal/goit-big-boom-team-project pull request #7
Opened 2022-12-17 19:51 UTC by Ivannavi12345

прошу простіть і понять

2022-12-17 21:21 UTC, OlhaMal requested changes

2022-12-17 21:21 UTC, OlhaMal commented on src/partials/hero.html
> +<section class="hero">
написати вище не можу, але навіщо ти завантажив 3 варіанти свг кнопки в папку images? свг - це просто намальовані браузером лінії по інструкції - їх не потрібно пару разів скачувати. Добав будь ласка будь-яку версію в спрайт (якщо той що я загрузила не такий як тобі треба - заміни його) і шлях пропиши звідти. Прописується він теж один раз, бо свг нема різниці який дисплей.

2022-12-17 21:21 UTC, OlhaMal commented on src/partials/hero.html
> +      <h1 class="hero__title">ANEMONE</h1>
напиши будь ласка не `ANEMONE`, a `Anemone`.

2022-12-17 21:21 UTC, OlhaMal commented on src/sass/components/_hero.scss
> +.hero__title {
а тут задай `text-transform: uppercase;`

2022-12-17 21:21 UTC, OlhaMal commented on src/sass/components/_hero.scss
> +    background-image: url(/hero/btnphone.svg);
`url(/hero/btnphone.svg);` тут має бути крапка `url(./hero/btnphone.svg);`
але воно тобі взагалі не потрібне, просто написала, до слова

2022-12-17 21:21 UTC, OlhaMal commented on src/sass/components/_hero.scss
> +  @media screen and(min-width: $tablet) {
`@media screen and(min-width: $tablet)` в тебе після `and` то є пробіл то нема
краще щоб був (але я чесно не знаю чи то на щось впливає, просто красиво)

2022-12-18 12:46 UTC, Ivannavi12345 commented on src/partials/hero.html
> +<section class="hero">
пофіксив

2022-12-18 12:47 UTC, Ivannavi12345 commented
пофіксив

2022-12-18 17:26 UTC, OlhaMal approved these changes, later dismissed

2022-12-18 17:27 UTC, OlhaMal approved these changes

2022-12-18 17:27 UTC, merged